### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [andela/ah-the-immortals-frontend#42]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/andela/ah-the-immortals-frontend/blob/develop/package.json#L71

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by koechkevin** [comment]
Thanks @DanielRuf  for your heads up. We will look into this
